[package]
name = "media-cli"
version = "0.2.0"
edition = "2021"
rust-version = "1.85"
authors = ["Sqrilizz <sqrilizz@users.noreply.github.com>"]
description = "Universal CLI media player for YouTube, Twitch, Anime and local files"
repository = "https://github.com/sqrilizz/media-cli"
license = "MIT"

[dependencies]
clap = { version = "=4.5.48", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
anyhow = "1.0"
walkdir = "2.5"
crossterm = "0.27"
ratatui = "0.26"
rand = "0.8"
aes = "0.8"
base64 = "0.22"
ctr = "0.9"
sha2 = "0.10"
unicode-segmentation = "=1.12.0"
ureq = { version = "=2.12.1", features = ["json"] }

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = true
